apiVersion: batch/v1
kind: Job
metadata:
  name: rse-create-secret
  namespace: {{ .Values.global.namespace }}
spec:
  template:
    spec:
      serviceAccountName: {{ .Values.oc.serviceaccount }}
      serviceAccount: {{ .Values.oc.serviceaccount }}
      containers:
        - name: defsecret
          image: {{ .Values.oc.image }}
          command:
            - /bin/sh
            - -c
            - |
              DBPASSWORD=$(oc get secret sysml-pguser-postgres -n {{ .Values.global.namespace }} -o jsonpath='{.data.password}' )
              
              cat << EOF | oc apply -f -
              kind: Secret
              apiVersion: v1
              metadata:
                name: rse-application-secrets
                namespace: {{ .Values.global.namespace }}              
                annotations:
                  created-by-job: rse-create-secret
              data:
                dbPassword: $DBPASSWORD
                dbAdminPassword: $DBPASSWORD
                oidcClientId: $( echo sysmlv2-client | base64 )
                oidcClientSecret: $( echo KyilI7iW6W8KrbyUmYY86Y2J4tt9IiHY | base64 )
                oidcSigningKey: $( echo alskjdfsdfjidufHHKHFD | base64
              EOF
      restartPolicy: Never
