apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.global.jobName }}
  namespace: {{ .Values.global.namespaceIls }}
spec:
  template:
    spec:
      serviceAccountName: {{ .Values.global.serviceaccount }}
      serviceAccount: {{ .Values.global.serviceaccount }}
      containers:
        - name: defsecret
          image: {{ .Values.global.image }}
          command:
            - /bin/sh
            - -c
            - |
              DBPASSWORD=$(oc get secret sysml-pguser-postgres -n {{ .Values.global.namespace }} -o jsonpath='{.data.password}' | base64 -d)
              
              cat << EOF | oc apply -f -
              kind: Secret
              apiVersion: v1
              metadata:
                name: rse-application-secrets
                namespace: {{ .Values.global.namespace }}
              stringData:
                dbPassword: $DBPASSWORD
                dbAdminPassword: $DBPASSWORD
                oidcClientId: sysmlv2-client
                oidcClientSecret: KyilI7iW6W8KrbyUmYY86Y2J4tt9IiHY
                oidcSigningKey: alskjdfsdfjidufHHKHFD
              EOF
      restartPolicy: OnFailure
