apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: sysml
  namespace: {{ global.namespace }}
spec:
  image: {{ rse.image }}
  backups:
    pgbackrest:
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
  instances:
  - dataVolumeClaimSpec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
    name: ""
    replicas: 1
  openshift: true
  patroni:
    leaderLeaseDurationSeconds: 30
    port: 8008
    syncPeriodSeconds: 10
  port: 5432
  postgresVersion: 17
  proxy:
    pgBouncer:
      port: 5432
      replicas: 1
  users:
  - name: postgres
    databases:
      - sysml
    options: SUPERUSER
  - name: pgadmin
    databases:
      - sysml
