while [ $( oc get po --no-headers  -n {{ namespace }} | grep sysml  |grep Running  |  egrep '2/2|4/4'  | wc -l ) -lt 3 ]
do
    oc get po --no-headers  -n {{ namespace }} | grep sysml
    sleep 10
done

while [ $( oc get po --no-headers  -n {{ namespace }} | grep sysml-backup  |grep Completed  |  grep '0/1'  | wc -l ) -lt 1 ]
do
    oc get po --no-headers  -n {{ namespace }} | grep sysml-backup
    sleep 10
done

DBPASSWORD=$(oc get secret sysml-pguser-postgres -n $NAMESPACE -o jsonpath='{.data.password}' | base64 -d)

cat << EOF | oc apply -f -
kind: Secret
apiVersion: v1
metadata:
  name: rse-application-secrets
  namespace: $NAMESPACE
stringData:
  dbPassword: $DBPASSWORD
  dbAdminPassword: $DBPASSWORD
  oidcClientId: sysmlv2-client
  oidcClientSecret: KyilI7iW6W8KrbyUmYY86Y2J4tt9IiHY
  oidcSigningKey: alskjdfsdfjidufHHKHFD
EOF
