apiVersion: rhapsodyse.ibm.com/v1
kind: RhapsodySEApp
metadata:
  name: rhapsodyseapp
  namespace: {{ namespace }}
spec:
  ## Accept IBM Rhapsody SE license by setting the value as true.
  acceptLicense: true

  ## Licensing configuration
  licensing:
   #lingerTimeDefault: 1800
   #licensesExpirySecs: 4
    server:
      host: license_server
      id: 0242ac1100021
      port: 27000
    vendor:
      id: ibmratl
      port: 27002
