apiVersion: batch/v1
kind: Job
metadata:
  name: rse-load-license
  namespace: {{ .Values.global.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1" 
spec:
  template:
    spec:
      serviceAccountName: {{ .Values.oc.serviceaccount }}
      serviceAccount: {{ .Values.oc.serviceaccount }}
      containers:
        - name: loadlicense
          image: {{ .Values.oc.image }}
          command:
            - /bin/sh
            - -c
            - |
              DBPASSWORD=$(oc get secret sysml-pguser-postgres -n {{ .Values.global.namespace }} -o jsonpath='{.data.password}' )
              lb64=$(oc get secret rse-create-secret -n {{ .Values.global.namespace }} -o jsonpath='{.data.token}')
              curl -i  -k -X POST {{ .Values.api.url }}  \
                  -H "Content-Type: application/json" \
                  -H 'Accept: application/json' \
                  -H "Authorization: {{ .Values.auth.token }} " \
                  --data '{"token": "{{ $lb64 | b64dec "}'

              
      restartPolicy: Never
