apiVersion: batch/v1
kind: Job
metadata:
  name: rse-load-license
  namespace: {{ .Values.global.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1" 
spec:
  template:
    spec:
      serviceAccountName: {{ .Values.oc.serviceaccount }}
      serviceAccount: {{ .Values.oc.serviceaccount }}
      volumes:
      - name: tokenli
        secret:
          secretName: {{ .Values.license.secret }}
      - name: tokenauth
        secret:
          secretName: {{ .Values.auth.secret }}
      containers:
        - name: loadlicense
          image: {{ .Values.oc.image }}
          volumeMounts:
          - name: tokenli
            mountPath: /tmp/tokenli
            subPath: token
            readOnly: true
          - name: tokenauth
            mountPath: /tmp/tokenauth
            subPath: token
            readOnly: true
          command:
            - /bin/sh
            - -xv
            - -c
            - |           
              STATUS=$(curl  -s -o /dev/null -k -X POST {{ .Values.api.url }}  \
                  -H "Content-Type: application/json" \
                  -H 'Accept: application/json' \
                  -H "Authorization: $(cat /tmp/tokenauth )" \
                  --data "{\"token\": \"$( cat /tmp/tokenli )\" }" )
            
              if [ "$STATUS" -eq 200 ]; then
                 echo "Success"
                 exit 0
              else
                 echo "Failed with status $STATUS"
                 exit 1
              fi
      restartPolicy: Never
