apiVersion: project.openshift.io/v1
kind: Project
metadata:
  annotations:
    openshift.io/description: ""
    openshift.io/display-name: ""
    openshift.io/requester: kube:admin
    openshift.io/sa.scc.mcs: s0:c29,c9
    openshift.io/sa.scc.supplemental-groups: 1000830000/10000
    openshift.io/sa.scc.uid-range: 1000830000/10000
  labels:
    kubernetes.io/metadata.name: {{ .Values.global.namespace }}
    openshift-pipelines.tekton.dev/namespace-reconcile-version: 1.20.0
    openshift-pipelines.tekton.dev/namespace-trusted-configmaps-version: 1.20.0
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: baseline
    pod-security.kubernetes.io/warn-version: latest
  name: {{ .Values.global.namespace }}
spec:
  finalizers:
  - kubernetes
